### ISSUE TITLE
Error in NapsterSessionManager, can't complete login flow

### ISSUE THREAD

**Issue by jeserodz** [Napster/napster-android-sdk#3]
Hi @reud, 

From last week I'm having an issue to complete the auth process as demonstrated in your examples. Communication with API seems to be working fine, because I'm able to get `accessToken`, `refreshToken`, expiration time and user account data. But the `NapsterSessionManager` returns this error and the the app force closes:

```
E/AndroidRuntime: FATAL EXCEPTION: Thread-673
  Process: com.napster.cedar.sample.stationplayer, PID: 24002
  java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
    at com.napster.cedar.NapsterError.<init>(SourceFile:36)
    at com.napster.cedar.session.internal.NapsterSessionManager$UserResponseCallback.failure(SourceFile:208)
    at retrofit.CallbackRunnable$2.run(CallbackRunnable.java:53)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at com.napster.cedar.internal.service.ServiceModule$3$1.run(SourceFile:91)
    at java.lang.Thread.run(Thread.java:818
```
This is also happening with the example app provided in the documentation. Any help would be appreciated. 

Thanks!

**Comment by 7280423** [comment]
In class  define @SerializedName("expirationDate") public final long b; is long type， However, the network interface returns ("expirationDate": "2018-05-16T07:00:00.000Z") is String type。
They seem to have no maintenance
